# Generated by Django 3.2.5 on 2021-08-03 16:06

import cashier.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[cashier.profiles.models.validate_even]),
        ),
    ]
