# Generated by Django 3.2.5 on 2021-08-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='household',
        ),
    ]
