# Generated by Django 3.2.5 on 2021-08-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_alter_householdprofile_apartment'),
        ('profiles', '0006_userprofile_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='households.householdprofile'),
        ),
    ]
