# Generated by Django 3.2.5 on 2021-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdprofile',
            name='apartment',
            field=models.IntegerField(null=True),
        ),
    ]
