# Generated by Django 3.2.5 on 2021-08-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_individualpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsadmin',
            name='curr_month',
            field=models.IntegerField(default=8),
        ),
    ]
