# Generated by Django 3.2.5 on 2021-08-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_salariespayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualpayment',
            name='April',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='August',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='December',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='February',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='January',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='July',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='June',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='March',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='May',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='November',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='October',
        ),
        migrations.RemoveField(
            model_name='individualpayment',
            name='September',
        ),
    ]
