# Generated by Django 3.2.5 on 2021-08-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20210808_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpayment',
            name='April',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='August',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='December',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='February',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='January',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='July',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='June',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='March',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='May',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='November',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='October',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualpayment',
            name='September',
            field=models.BooleanField(default=False),
        ),
    ]
