# Generated by Django 3.2.5 on 2021-08-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20210808_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTaxesPayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('January', models.IntegerField(default=0)),
                ('February', models.IntegerField(default=0)),
                ('March', models.IntegerField(default=0)),
                ('April', models.IntegerField(default=0)),
                ('May', models.IntegerField(default=0)),
                ('June', models.IntegerField(default=0)),
                ('July', models.IntegerField(default=0)),
                ('August', models.IntegerField(default=0)),
                ('September', models.IntegerField(default=0)),
                ('October', models.IntegerField(default=0)),
                ('November', models.IntegerField(default=0)),
                ('December', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
